// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import type { TeamsFact, TeamsOverview, TeamsRecallResponse, TeamsRosterRow } from "@/lib/api";

// STUDIO-681 §10, sub-ticket 4 — the Memory page's acceptance boxes 4.1 … 4.6, driven through
// the real view against the endpoints §9 has: `GET /api/v1/teams` for the roster and the memory
// backend, `GET /api/v1/teams/recall` (empty query = browse) for each teammate's bank, and
// `POST /api/v1/teams/invalidate` for the correction.

const h = vi.hoisted(() => ({
  fetchTeamsOverview: vi.fn(),
  fetchTeamsRecall: vi.fn(),
  postTeamsInvalidate: vi.fn(),
}));

vi.mock("@/lib/api", async (orig) => {
  const actual = await orig<typeof import("@/lib/api")>();
  return {
    ...actual,
    fetchTeamsOverview: h.fetchTeamsOverview,
    fetchTeamsRecall: h.fetchTeamsRecall,
    postTeamsInvalidate: h.postTeamsInvalidate,
  };
});

const { MemoryView } = await import("./MemoryView");

function fact(over: Partial<TeamsFact> & Pick<TeamsFact, "id" | "identity">): TeamsFact {
  return {
    document_id: "run-1",
    ticket: "STUDIO-654",
    commit_sha: "",
    pr: "",
    run_id: "1",
    at: "2026-08-31T19:11:00Z",
    state: "valid",
    reason: "",
    content: "a retained observation",
    ...over,
  };
}

function rosterRow(name: string): TeamsRosterRow {
  return {
    name,
    profile: "swe",
    labels: [],
    bank: `agent-${name}`,
    max_concurrent: 0,
    live_runs: 0,
    tickets: [],
  };
}

const ALICE_FACTS: TeamsFact[] = [
  fact({
    id: "a1",
    identity: "alice",
    ticket: "STUDIO-654",
    run_id: "547",
    commit_sha: "44d8675cafebabe",
    at: "2026-08-31T19:11:00Z",
    content: "The config.go rebase hazard matters more than the fix.",
  }),
  fact({
    id: "a2",
    identity: "alice",
    ticket: "STUDIO-654",
    run_id: "545",
    at: "2026-08-31T16:54:00Z",
    content: "The vision Router picks the model by input shape.",
  }),
];

const JIMMY_FACTS: TeamsFact[] = [
  fact({
    id: "j1",
    identity: "jimmy",
    ticket: "STUDIO-676",
    run_id: "546",
    at: "2026-08-31T21:15:00Z",
    content: "mobile/ios and mobile/android are gitignored and regenerated by expo prebuild.",
  }),
];

const OVERVIEW: TeamsOverview = {
  enabled: true,
  manager_mode: "labels+model",
  default_identity: "",
  backend: "local",
  roster: [rosterRow("alice"), rosterRow("jimmy")],
};

interface Harness {
  onNavigate?: (route: "job", key: string) => void;
  onReinstate?: (fact: TeamsFact) => Promise<void>;
}

function mount(over: Harness = {}) {
  const client = new QueryClient({
    defaultOptions: { queries: { retry: false }, mutations: { retry: false } },
  });
  return render(
    <QueryClientProvider client={client}>
      <MemoryView onNavigate={over.onNavigate ?? (() => {})} onReinstate={over.onReinstate} />
    </QueryClientProvider>,
  );
}

function seed(overview: TeamsOverview = OVERVIEW) {
  h.fetchTeamsOverview.mockResolvedValue(overview);
  h.fetchTeamsRecall.mockImplementation(
    async (identity: string): Promise<TeamsRecallResponse> => ({
      identity,
      facts: identity === "alice" ? ALICE_FACTS : identity === "jimmy" ? JIMMY_FACTS : [],
      skipped: [],
    }),
  );
  h.postTeamsInvalidate.mockImplementation(
    async (identity: string, factID: string, reason: string) => ({
      identity,
      fact_id: factID,
      invalidated: true,
      reason,
    }),
  );
}

/** The fact cards currently on screen, in render order. */
function cards(): HTMLElement[] {
  return screen.queryAllByRole("article");
}

/** The card whose body contains `text`. */
async function card(text: string): Promise<HTMLElement> {
  return await waitFor(() => {
    const found = cards().find((el) => el.textContent?.includes(text));
    if (found === undefined) throw new Error(`no fact card containing ${JSON.stringify(text)}`);
    return found;
  });
}

async function settled() {
  await waitFor(() => expect(cards()).toHaveLength(3));
}

function stat(label: string): string {
  const el = screen.getByText(label, { selector: ".stat .l" });
  return within(el.parentElement as HTMLElement).getByText(/^\d+$/).textContent ?? "";
}

afterEach(() => {
  cleanup();
  vi.clearAllMocks();
});

describe("Memory page", () => {
  it("4.1 — shows facts, valid, invalidated and banks from the bank data", async () => {
    seed();
    mount();
    await settled();
    expect(stat("facts")).toBe("3");
    expect(stat("valid")).toBe("3");
    expect(stat("invalidated")).toBe("0");
    expect(stat("banks")).toBe("2");
  });

  it("4.1 — browses EVERY roster member's bank, because recall reads one identity at a time", async () => {
    seed();
    mount();
    await settled();
    expect(h.fetchTeamsRecall).toHaveBeenCalledWith("alice", "");
    expect(h.fetchTeamsRecall).toHaveBeenCalledWith("jimmy", "");
  });

  it("4.2 — search filters by free text", async () => {
    seed();
    mount();
    await settled();
    fireEvent.change(screen.getByLabelText("Search facts"), { target: { value: "expo prebuild" } });
    await waitFor(() => expect(cards()).toHaveLength(1));
    expect(cards()[0].textContent).toContain("expo prebuild");
  });

  it("4.2 — search filters by ticket key", async () => {
    seed();
    mount();
    await settled();
    fireEvent.change(screen.getByLabelText("Search facts"), { target: { value: "STUDIO-676" } });
    await waitFor(() => expect(cards()).toHaveLength(1));
    expect(cards()[0].textContent).toContain("STUDIO-676");
  });

  it("4.2 — search filters by the SHA the card actually shows", async () => {
    seed();
    mount();
    await settled();
    fireEvent.change(screen.getByLabelText("Search facts"), { target: { value: "44d8675" } });
    await waitFor(() => expect(cards()).toHaveLength(1));
    expect(cards()[0].textContent).toContain("rebase hazard");
  });

  it("4.3 — the teammate filter narrows the list", async () => {
    seed();
    mount();
    await settled();
    fireEvent.change(screen.getByLabelText("Filter memory by teammate"), {
      target: { value: "jimmy" },
    });
    await waitFor(() => expect(cards()).toHaveLength(1));
    expect(cards()[0].textContent).toContain("expo prebuild");
  });

  it("4.3 — the ticket filter narrows the list", async () => {
    seed();
    mount();
    await settled();
    fireEvent.change(screen.getByLabelText("Filter memory by ticket"), {
      target: { value: "STUDIO-654" },
    });
    await waitFor(() => expect(cards()).toHaveLength(2));
  });

  it("4.3 — the state Seg narrows to valid and to invalidated", async () => {
    seed();
    mount();
    await settled();
    const seg = screen.getByRole("group", { name: "Filter memory by state" });
    fireEvent.click(within(seg).getByRole("button", { name: "Valid" }));
    await waitFor(() => expect(cards()).toHaveLength(3));
    fireEvent.click(within(seg).getByRole("button", { name: "Invalidated" }));
    await waitFor(() => expect(cards()).toHaveLength(0));
  });

  it("4.3 — the sort Select reorders the list", async () => {
    seed();
    mount();
    await settled();
    const newest = cards().map((c) => c.getAttribute("data-fact"));
    expect(newest).toEqual(["jimmy/j1", "alice/a1", "alice/a2"]);
    fireEvent.change(screen.getByLabelText("Sort memory"), { target: { value: "oldest" } });
    await waitFor(() =>
      expect(cards().map((c) => c.getAttribute("data-fact"))).toEqual([...newest].reverse()),
    );
  });

  it("4.4 — a card renders the teammate, its ticket/run/SHA chips, backend badge, provenance and body", async () => {
    seed();
    mount();
    const c = await card("rebase hazard");
    const q = within(c);
    expect(q.getByText("alice")).toBeTruthy();
    expect(q.getByText("STUDIO-654")).toBeTruthy();
    expect(q.getByText("run 547")).toBeTruthy();
    expect(q.getByText("44d8675")).toBeTruthy();
    expect(q.getByText("local")).toBeTruthy();
    expect(q.getByText(/host-stamped · agent-alice · valid/)).toBeTruthy();
    expect(c.textContent).toContain("The config.go rebase hazard matters more than the fix.");
  });

  it("4.4 — View run routes to that fact's ticket", async () => {
    seed();
    const onNavigate = vi.fn();
    mount({ onNavigate });
    const c = await card("expo prebuild");
    fireEvent.click(within(c).getByRole("button", { name: "View run 546" }));
    expect(onNavigate).toHaveBeenCalledWith("job", "STUDIO-676");
  });

  it("4.5 — Invalidate captures a reason and moves the fact to invalidated, dimmed with a banner", async () => {
    seed();
    mount();
    const c = await card("rebase hazard");
    fireEvent.click(within(c).getByRole("button", { name: "Invalidate" }));

    const why = within(c).getByLabelText("Why is this wrong?");
    fireEvent.change(why, { target: { value: "the hazard was fixed in #229" } });
    fireEvent.click(within(c).getByRole("button", { name: "Confirm invalidate" }));

    await waitFor(() =>
      expect(h.postTeamsInvalidate).toHaveBeenCalledWith("alice", "a1", "the hazard was fixed in #229"),
    );

    const dead = await card("rebase hazard");
    await waitFor(() => expect(dead.className).toContain("dead"));
    expect(within(dead).getByRole("status").textContent).toContain("the hazard was fixed in #229");
    await waitFor(() => expect(stat("invalidated")).toBe("1"));
    expect(stat("valid")).toBe("2");
  });

  it("4.5 — keeps the dimmed card when the refetch answers without the record", async () => {
    seed();
    mount();
    const c = await card("rebase hazard");

    // What the real daemon does the instant the correction lands: recall serves VALID records
    // only, so the record the operator just invalidated stops being returned. The card carries
    // the undo, so it has to survive the refetch the invalidate itself triggers.
    h.fetchTeamsRecall.mockImplementation(async (identity: string) => ({
      identity,
      facts: identity === "alice" ? ALICE_FACTS.filter((f) => f.id !== "a1") : JIMMY_FACTS,
      skipped: [],
    }));

    fireEvent.click(within(c).getByRole("button", { name: "Invalidate" }));
    fireEvent.change(within(c).getByLabelText("Why is this wrong?"), { target: { value: "stale" } });
    fireEvent.click(within(c).getByRole("button", { name: "Confirm invalidate" }));

    await waitFor(() => expect(h.fetchTeamsRecall.mock.calls.length).toBeGreaterThan(2));

    const dead = await card("rebase hazard");
    await waitFor(() => expect(dead.className).toContain("dead"));
    expect(within(dead).getByRole("button", { name: "Reinstate" })).toBeTruthy();
    await waitFor(() => expect(stat("invalidated")).toBe("1"));
    expect(stat("facts")).toBe("3");
  });

  it("4.5 — a reasonless invalidate is refused, because the daemon refuses it too", async () => {
    seed();
    mount();
    const c = await card("rebase hazard");
    fireEvent.click(within(c).getByRole("button", { name: "Invalidate" }));
    expect(within(c).getByRole("button", { name: "Confirm invalidate" })).toHaveProperty(
      "disabled",
      true,
    );
    fireEvent.change(within(c).getByLabelText("Why is this wrong?"), { target: { value: "   " } });
    expect(within(c).getByRole("button", { name: "Confirm invalidate" })).toHaveProperty(
      "disabled",
      true,
    );
    expect(h.postTeamsInvalidate).not.toHaveBeenCalled();
  });

  it("4.5 — a rejected invalidate leaves the fact valid and says why", async () => {
    seed();
    h.postTeamsInvalidate.mockRejectedValue(new Error("teams_disabled: teams is off"));
    mount();
    const c = await card("rebase hazard");
    fireEvent.click(within(c).getByRole("button", { name: "Invalidate" }));
    fireEvent.change(within(c).getByLabelText("Why is this wrong?"), { target: { value: "wrong" } });
    fireEvent.click(within(c).getByRole("button", { name: "Confirm invalidate" }));

    await waitFor(() => expect(within(c).getByRole("alert").textContent).toContain("teams is off"));
    expect(c.className).not.toContain("dead");
    expect(stat("invalidated")).toBe("0");
  });

  it("4.6 — an invalidated fact shows Reinstate, which restores it to valid", async () => {
    seed();
    const reinstated: TeamsFact[] = [];
    const onReinstate = vi.fn(async (fact: TeamsFact) => {
      reinstated.push(fact);
    });
    mount({ onReinstate });

    const c = await card("rebase hazard");
    fireEvent.click(within(c).getByRole("button", { name: "Invalidate" }));
    fireEvent.change(within(c).getByLabelText("Why is this wrong?"), { target: { value: "stale" } });
    fireEvent.click(within(c).getByRole("button", { name: "Confirm invalidate" }));
    await waitFor(() => expect(stat("invalidated")).toBe("1"));

    const dead = await card("rebase hazard");
    fireEvent.click(within(dead).getByRole("button", { name: "Reinstate" }));

    await waitFor(() => expect(onReinstate).toHaveBeenCalledTimes(1));
    expect(reinstated[0]).toMatchObject({ id: "a1", identity: "alice" });

    const alive = await card("rebase hazard");
    await waitFor(() => expect(alive.className).not.toContain("dead"));
    expect(within(alive).queryByRole("status")).toBeNull();
    await waitFor(() => expect(stat("invalidated")).toBe("0"));
    expect(stat("valid")).toBe("3");
    // Reversible means the correction can be made again, not that the fact is now unmarkable.
    expect(within(alive).getByRole("button", { name: "Invalidate" })).toBeTruthy();
  });

  it("4.6 — with no reinstate capability the fact stays invalidated and says what is missing", async () => {
    seed();
    mount();
    const c = await card("rebase hazard");
    fireEvent.click(within(c).getByRole("button", { name: "Invalidate" }));
    fireEvent.change(within(c).getByLabelText("Why is this wrong?"), { target: { value: "stale" } });
    fireEvent.click(within(c).getByRole("button", { name: "Confirm invalidate" }));
    await waitFor(() => expect(stat("invalidated")).toBe("1"));

    const dead = await card("rebase hazard");
    fireEvent.click(within(dead).getByRole("button", { name: "Reinstate" }));

    await waitFor(() => expect(within(dead).getByRole("alert").textContent).toMatch(/endpoint/i));
    expect(dead.className).toContain("dead");
    expect(stat("invalidated")).toBe("1");
  });

  it("reports a bank it could not read rather than showing an empty page", async () => {
    h.fetchTeamsOverview.mockResolvedValue(OVERVIEW);
    h.fetchTeamsRecall.mockImplementation(async (identity: string) => {
      if (identity === "jimmy") throw new Error("memory_backend_error: bank unreadable");
      return { identity, facts: ALICE_FACTS, skipped: [] };
    });
    mount();
    await waitFor(() => expect(cards()).toHaveLength(2));
    expect(screen.getByRole("alert").textContent).toContain("bank unreadable");
  });

  it("says the banks are empty rather than rendering a bare page", async () => {
    h.fetchTeamsOverview.mockResolvedValue({ ...OVERVIEW, roster: [] });
    h.fetchTeamsRecall.mockResolvedValue({ identity: "", facts: [], skipped: [] });
    mount();
    await waitFor(() => expect(screen.getByText(/no facts/i)).toBeTruthy());
    expect(h.fetchTeamsRecall).not.toHaveBeenCalled();
  });
});
