#!/usr/bin/env bash
# Confirm the build consumed the source icon into the app's .icns (Contents/Resources/*.icns).
# Parity port of $REF/desktop/scripts/verify-icon.sh, adapted from Wails to Tauri: Wails regenerated
# `iconfile.icns` from build/appicon.png on every build; the Tauri bundler copies the configured
# `bundle.icon` .icns (src-tauri/icons/icon.icns, generated by `cargo tauri icon`) into the bundle as
# `Contents/Resources/icon.icns`. This asserts that artifact is present, is a real Apple icon, and
# (best effort) carries a layer at the source resolution — so a stale, empty, or missing icon can't
# slip through unnoticed. Invoked by `make verify-icon` / `make dmg`.
#
# Usage: verify-icon.sh <App.app> <source-icon.(icns|png)>
set -euo pipefail

APP="${1:?usage: verify-icon.sh <App.app> <source-icon>}"
SRC="${2:?usage: verify-icon.sh <App.app> <source-icon>}"

fail() { echo "verify-icon: FAIL: $*" >&2; exit 1; }

[ -d "$APP" ] || fail "app bundle not found: $APP (run 'make app' first)"

# The Tauri bundler names the macOS icon after the configured .icns (icon.icns); glob so a future
# rename still resolves. Exactly one .icns is expected in a well-formed bundle.
ICNS="$(ls "$APP/Contents/Resources/"*.icns 2>/dev/null | head -1 || true)"
[ -n "$ICNS" ]  || fail "no .icns in $APP/Contents/Resources (the bundler should copy bundle.icon's icns)"
[ -s "$ICNS" ]  || fail "icon is empty: $ICNS"

# Must be a real Apple icon file, not a stray copy of the source PNG.
file "$ICNS" | grep -qi "Mac OS X icon" || fail "$ICNS is not a Mac OS X icon file"

echo "verify-icon: $ICNS present ($(wc -c < "$ICNS" | tr -d ' ') bytes, valid icns)"

# Deep check (best-effort): the icns must decode and carry a layer at least as large as the source.
# Degrade gracefully if the macOS image tools are unavailable rather than failing the build.
if command -v iconutil >/dev/null 2>&1 && command -v sips >/dev/null 2>&1; then
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT
  if iconutil -c iconset "$ICNS" -o "$tmp/icon.iconset" >/dev/null 2>&1; then
    big="$(ls -S "$tmp/icon.iconset/"*.png 2>/dev/null | head -1)"
    if [ -n "$big" ]; then
      pxwidth() { sips -g pixelWidth "$1" 2>/dev/null | awk '/pixelWidth/{print $2}'; }
      iw="$(pxwidth "$big")"
      if [ -f "$SRC" ]; then
        case "$SRC" in
          *.png) sw="$(pxwidth "$SRC")" ;;
          *)     sw="" ;; # an .icns source has no single pixel width; skip the comparison
        esac
        if [ -n "$sw" ] && [ -n "$iw" ]; then
          echo "verify-icon: source $SRC = ${sw}px; icns largest layer = ${iw}px"
          # The icns may carry MORE resolutions than the source (Retina @2x layers), so require the
          # largest icns layer to be at least the source width — catches a truncated/stale icon.
          [ "$iw" -ge "$sw" ] \
            || fail "icns largest layer (${iw}px) < source (${sw}px); icon may be stale — rebuild clean (rm -rf target/release/bundle && make app)"
        else
          echo "verify-icon: icns largest layer = ${iw:-?}px (source width unavailable; skipping comparison)"
        fi
      else
        echo "verify-icon: icns largest layer = ${iw:-?}px (source $SRC not found; skipping comparison)"
      fi
    fi
  else
    echo "verify-icon: note: iconutil could not decode $ICNS for the deep check; presence/validity OK"
  fi
else
  echo "verify-icon: note: iconutil/sips unavailable; skipped deep dimension check"
fi

echo "verify-icon: OK — the app icon was generated from $SRC"
